version: '2.4'

services:
  vyos:
    build:
      context: .
    hostname: vyos
    privileged: true
    entrypoint: ['/sbin/init']
    volumes:
      - /lib/modules:/lib/modules
    ports:
      - 2222:22/tcp
    networks:
      - vyos
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
networks:
  vyos:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 192.0.2.0/24
        - subnet: 2001:db8::/32
